#!/usr/bin/env python3
"""
fit_trajectory.py

Merged pipeline for cricket ball detection, trajectory fitting, and
release speed estimation from behind-the-stumps iPhone footage.

Pipeline stages:
  1. YOLO + ByteTrack + HSV recovery  ->  per-frame detections (CSV)
  2. IMM + UKF on detections          ->  release speed (km/h)
  3. Parabolic trajectory smoothing    ->  cleaned trajectory
  4. Overlay rendering                 ->  annotated output video

Dependencies:
    pip install ultralytics opencv-python numpy pandas scipy
"""

from pathlib import Path
import csv
import math
import numpy as np
import cv2
import pandas as pd
from scipy.linalg import cholesky
from ultralytics import YOLO


# ─── File paths ──────────────────────────────────────────────────────────────

MODEL_PATH   = "best3.onnx"
VIDEO_PATH   = "input5.mov"
OUT_DIR      = "run_output"
OUTPUT_VIDEO = "run_output/hsv_imm_output.mp4"

# ─── YOLO detector ──────────────────────────────────────────────────────────

IMGSZ   = 1280
CONF    = 0.20
IOU     = 0.7
DEVICE  = None
CLASSES = [0]

# ─── ByteTrack tracker ──────────────────────────────────────────────────────

TRACK_BUFFER      = 90
TRACK_HIGH_THRESH = 0.35
TRACK_LOW_THRESH  = 0.05
NEW_TRACK_THRESH  = 0.45
MATCH_THRESH      = 0.80

# ─── Motion gating ──────────────────────────────────────────────────────────

GATE_RADIUS_PX     = 80
GATE_GROW_PER_MISS = 15
MAX_MISSES         = 60
MIN_BOX_AREA_PX    = 25

# ─── HSV blob recovery ──────────────────────────────────────────────────────

ENABLE_HSV_RECOVERY = True
HSV_H_MARGIN     = 12
HSV_S_MARGIN     = 70
HSV_V_MARGIN     = 70
HSV_MIN_S        = 40
HSV_MIN_V        = 40
HSV_ROI_PAD_PX   = 40
HSV_MIN_AREA_PX  = 6
HSV_MAX_AREA_PX  = 2000
HSV_ASPECT_MIN   = 0.35
HSV_ASPECT_MAX   = 2.8
HSV_MORPH_KERNEL = 3
HSV_MORPH_ITERS  = 1

# ─── Trajectory overlay ─────────────────────────────────────────────────────

LINE_COLOR       = (0, 140, 255)
MIN_POINTS       = 5
BOUNCE_THRESHOLD = 8
ANGLE_CUTOFF     = 45

# ─── Camera intrinsics & extrinsics ─────────────────────────────────────────
# Focal length calibrated from iPhone sensor crop factor.
# Tilt measured via pitch geometry: 4.19 deg gives correct horizon line.

GRAVITY      = 9.81
BALL_RADIUS  = 0.036
PITCH_LENGTH = 20.50              # full pitch crease-to-crease + roughly 30 cm to account for camera spacing (metres)

CAM_FOCAL_PX  = 1371.0
CAM_CX        = 960.0
CAM_CY        = 540.0
CAM_IMG_W     = 1920
CAM_IMG_H     = 1080
CAM_POS_WORLD = np.array([-2.0, 0.0, 0.71])
CAM_TILT_DEG  = 4.19              # measured tilt angle (degrees)

# ─── UKF tuning ─────────────────────────────────────────────────────────────

UKF_ALPHA = 1e-3
UKF_BETA  = 2.0
UKF_KAPPA = 0.0

MEAS_SIGMA_DET  = 3.0             # pixel noise for YOLO detections
MEAS_SIGMA_HSV  = 8.0             # pixel noise for HSV recoveries
MEAS_SIGMA_NONE = 1e6             # effectively ignore missing frames

# ─── IMM mode transition matrix ─────────────────────────────────────────────
# Two modes only: pre-bounce ballistic and occluded/coast.
# High self-transition keeps the filter in ballistic until evidence of loss.

IMM_TRANSITION = np.array([
    [0.95, 0.05],
    [0.15, 0.85],
])


# ═══════════════════════════════════════════════════════════════════════════════
# TRACKING HELPERS
# ═══════════════════════════════════════════════════════════════════════════════

def write_bytetrack_yaml(path: Path):
    """Dump a ByteTrack config YAML to disk for ultralytics."""
    y = f"""# Auto-generated ByteTrack config
tracker_type: bytetrack
track_high_thresh: {TRACK_HIGH_THRESH}
track_low_thresh: {TRACK_LOW_THRESH}
new_track_thresh: {NEW_TRACK_THRESH}
track_buffer: {TRACK_BUFFER}
match_thresh: {MATCH_THRESH}
fuse_score: true
"""
    path.write_text(y, encoding="utf-8")


def area_xyxy(x1, y1, x2, y2) -> float:
    return max(0.0, x2 - x1) * max(0.0, y2 - y1)


def center_xyxy(x1, y1, x2, y2):
    return (0.5 * (x1 + x2), 0.5 * (y1 + y2))


def dist(a, b):
    return math.hypot(a[0] - b[0], a[1] - b[1])


def _clip_int(v, lo, hi):
    return int(max(lo, min(hi, v)))


def _roi_from_center(cx, cy, half, w, h):
    x1 = _clip_int(cx - half, 0, w - 1)
    y1 = _clip_int(cy - half, 0, h - 1)
    x2 = _clip_int(cx + half, 0, w - 1)
    y2 = _clip_int(cy + half, 0, h - 1)
    if x2 <= x1: x2 = min(w - 1, x1 + 1)
    if y2 <= y1: y2 = min(h - 1, y1 + 1)
    return x1, y1, x2, y2


def _learn_hsv_model(frame_bgr, xyxy):
    """
    Build a robust HSV range from pixels inside the chosen YOLO/track box.
    Handles red hue wrap-around by returning 1 or 2 hue ranges.
    """
    h, w = frame_bgr.shape[:2]
    x1, y1, x2, y2 = map(int, xyxy)
    x1 = _clip_int(x1, 0, w - 1); x2 = _clip_int(x2, 0, w - 1)
    y1 = _clip_int(y1, 0, h - 1); y2 = _clip_int(y2, 0, h - 1)
    if x2 <= x1 or y2 <= y1:
        return None

    crop = frame_bgr[y1:y2, x1:x2]
    if crop.size == 0:
        return None

    hsv = cv2.cvtColor(crop, cv2.COLOR_BGR2HSV)
    H = hsv[:, :, 0].astype(np.int32)
    S = hsv[:, :, 1].astype(np.int32)
    V = hsv[:, :, 2].astype(np.int32)

    good = (S >= HSV_MIN_S) & (V >= HSV_MIN_V)
    if good.sum() < 20:
        good = np.ones_like(H, dtype=bool)

    h_med = int(np.median(H[good]))
    s_med = int(np.median(S[good]))
    v_med = int(np.median(V[good]))

    s_lo = _clip_int(s_med - HSV_S_MARGIN, 0, 255)
    s_hi = _clip_int(s_med + HSV_S_MARGIN, 0, 255)
    v_lo = _clip_int(v_med - HSV_V_MARGIN, 0, 255)
    v_hi = _clip_int(v_med + HSV_V_MARGIN, 0, 255)

    h_lo = (h_med - HSV_H_MARGIN) % 180
    h_hi = (h_med + HSV_H_MARGIN) % 180

    if h_lo <= h_hi:
        hue_ranges = [((h_lo, s_lo, v_lo), (h_hi, s_hi, v_hi))]
    else:
        hue_ranges = [((0,    s_lo, v_lo), (h_hi, s_hi, v_hi)),
                      ((h_lo, s_lo, v_lo), (179,  s_hi, v_hi))]

    return {"hue_ranges": hue_ranges}


def _hsv_blob_in_roi(frame_bgr, roi_xyxy, hsv_model, pred_xy=None):
    """
    Threshold HSV in ROI, find best blob (closest to pred if given),
    return xyxy in FULL-FRAME coords.
    """
    if hsv_model is None:
        return None

    H, W = frame_bgr.shape[:2]
    rx1, ry1, rx2, ry2 = map(int, roi_xyxy)
    rx1 = _clip_int(rx1, 0, W - 1); rx2 = _clip_int(rx2, 0, W - 1)
    ry1 = _clip_int(ry1, 0, H - 1); ry2 = _clip_int(ry2, 0, H - 1)
    if rx2 <= rx1 or ry2 <= ry1:
        return None

    roi = frame_bgr[ry1:ry2, rx1:rx2]
    if roi.size == 0:
        return None

    hsv = cv2.cvtColor(roi, cv2.COLOR_BGR2HSV)

    mask = None
    for (lo, hi) in hsv_model["hue_ranges"]:
        lo = np.array(lo, dtype=np.uint8)
        hi = np.array(hi, dtype=np.uint8)
        m = cv2.inRange(hsv, lo, hi)
        mask = m if mask is None else cv2.bitwise_or(mask, m)

    s = hsv[:, :, 1]
    v = hsv[:, :, 2]
    mask = cv2.bitwise_and(mask, cv2.inRange(s, HSV_MIN_S, 255))
    mask = cv2.bitwise_and(mask, cv2.inRange(v, HSV_MIN_V, 255))

    k = HSV_MORPH_KERNEL
    if k >= 3:
        kernel = np.ones((k, k), np.uint8)
        mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN,  kernel, iterations=HSV_MORPH_ITERS)
        mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel, iterations=HSV_MORPH_ITERS)

    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    best = None
    best_score = float("inf")

    for c in contours:
        area = cv2.contourArea(c)
        if area < HSV_MIN_AREA_PX or area > HSV_MAX_AREA_PX:
            continue

        x, y, w, h = cv2.boundingRect(c)
        if w <= 0 or h <= 0:
            continue

        aspect = w / float(h)
        if aspect < HSV_ASPECT_MIN or aspect > HSV_ASPECT_MAX:
            continue

        cx = x + 0.5 * w
        cy = y + 0.5 * h

        if pred_xy is not None:
            px, py = pred_xy
            px -= rx1; py -= ry1
            score = math.hypot(cx - px, cy - py)
        else:
            score = area

        if score < best_score:
            best_score = score
            best = (x, y, x + w, y + h)

    if best is None:
        return None

    bx1, by1, bx2, by2 = best
    return (float(bx1 + rx1), float(by1 + ry1), float(bx2 + rx1), float(by2 + ry1))


# ═══════════════════════════════════════════════════════════════════════════════
# CAMERA MODEL
# ═══════════════════════════════════════════════════════════════════════════════

class CameraModel:
    """
    Pinhole camera sitting behind the stumps, looking down the pitch.
    Converts between 3D world coordinates and 2D pixel coordinates
    using the measured tilt angle and known focal length.
    """

    def __init__(self):
        self.fx = CAM_FOCAL_PX
        self.fy = CAM_FOCAL_PX
        self.cx = CAM_CX
        self.cy = CAM_CY

        # world axes: X = down-pitch, Y = lateral, Z = up
        # camera axes: right, down, forward -- so we rotate accordingly
        R_base = np.array([
            [0.0,  1.0,  0.0],
            [0.0,  0.0, -1.0],
            [1.0,  0.0,  0.0],
        ])

        t_rad = np.radians(CAM_TILT_DEG)
        R_tilt = np.array([
            [1.0, 0.0,           0.0          ],
            [0.0, np.cos(t_rad), -np.sin(t_rad)],
            [0.0, np.sin(t_rad),  np.cos(t_rad)],
        ])
        self.R = R_tilt @ R_base
        self.t = -self.R @ CAM_POS_WORLD

    def project(self, p_world):
        """3D world point to 2D pixel (u, v)."""
        p_cam = self.R @ p_world + self.t
        if p_cam[2] <= 0.01:
            p_cam[2] = 0.01        # avoid division by zero
        u = self.fx * p_cam[0] / p_cam[2] + self.cx
        v = self.fy * p_cam[1] / p_cam[2] + self.cy
        return np.array([u, v])

    def back_project_ray(self, u, v):
        """Pixel (u,v) to unit ray direction in world coordinates."""
        ray_cam = np.array([(u - self.cx)/self.fx, (v - self.cy)/self.fy, 1.0])
        ray_cam /= np.linalg.norm(ray_cam)
        ray_world = self.R.T @ ray_cam
        return ray_world / np.linalg.norm(ray_world)


# ═══════════════════════════════════════════════════════════════════════════════
# UKF + IMM  (simplified: release speed only, no bounce dynamics)
# ═══════════════════════════════════════════════════════════════════════════════

def _sigma_points(x, P):
    """
    Generate scaled unscented-transform sigma points and weights.
    Uses the standard Merwe parameterisation (alpha, beta, kappa).
    """
    n = len(x)
    lam = UKF_ALPHA**2 * (n + UKF_KAPPA) - n
    try:
        S = cholesky((n + lam) * P, lower=True)
    except np.linalg.LinAlgError:
        # covariance may lose positive-definiteness after many steps
        S = cholesky((n + lam) * (P + 1e-8 * np.eye(n)), lower=True)

    pts = np.zeros((2 * n + 1, n))
    pts[0] = x
    for i in range(n):
        pts[i + 1]     = x + S[:, i]
        pts[n + i + 1] = x - S[:, i]

    Wm = np.full(2 * n + 1, 1.0 / (2 * (n + lam)))
    Wc = np.full(2 * n + 1, 1.0 / (2 * (n + lam)))
    Wm[0] = lam / (n + lam)
    Wc[0] = lam / (n + lam) + (1 - UKF_ALPHA**2 + UKF_BETA)
    return pts, Wm, Wc


def _f_ballistic(x, dt):
    """Pure ballistic dynamics: constant horizontal velocity, gravity on Z."""
    X, Y, Z, VX, VY, VZ = x
    return np.array([
        X  + VX * dt,
        Y  + VY * dt,
        Z  + VZ * dt - 0.5 * GRAVITY * dt**2,
        VX,
        VY,
        VZ - GRAVITY * dt,
    ])


class UKFMode:
    """Single UKF filter bank entry. Owns state vector, covariance, and dynamics."""

    def __init__(self, name, f_func, Q, x0, P0, cam):
        self.name = name
        self.f    = f_func
        self.Q    = Q.copy()
        self.x    = x0.copy()
        self.P    = P0.copy()
        self.cam  = cam
        self.lik  = 1.0              # measurement likelihood, updated each step

    def predict(self, dt):
        """Propagate sigma points through this mode's dynamics model."""
        sig, Wm, Wc = _sigma_points(self.x, self.P)
        sig_pred = np.array([self.f(sig[i], dt) for i in range(len(sig))])

        # weighted mean and covariance of propagated points
        self.x = np.sum(Wm[:, None] * sig_pred, axis=0)
        self.P = self.Q.copy()
        for i in range(len(sig)):
            d = sig_pred[i] - self.x
            self.P += Wc[i] * np.outer(d, d)

    def update(self, z, R):
        """
        Standard UKF measurement update in pixel space.
        Returns the Mahalanobis distance for gating / likelihood.
        """
        sig, Wm, Wc = _sigma_points(self.x, self.P)
        z_sig  = np.array([self.cam.project(sig[i, :3]) for i in range(len(sig))])
        z_pred = np.sum(Wm[:, None] * z_sig, axis=0)

        # innovation covariance S and cross-covariance Pxz
        S   = R.copy()
        Pxz = np.zeros((6, 2))
        for i in range(len(sig)):
            dz = z_sig[i] - z_pred
            dx = sig[i] - self.x
            S   += Wc[i] * np.outer(dz, dz)
            Pxz += Wc[i] * np.outer(dx, dz)

        S_inv = np.linalg.inv(S)
        K     = Pxz @ S_inv
        innov = z - z_pred
        maha  = float(innov @ S_inv @ innov)

        self.x = self.x + K @ innov
        self.P = self.P - K @ S @ K.T
        self.P = 0.5 * (self.P + self.P.T)     # enforce symmetry

        det_S    = max(np.linalg.det(S), 1e-30)
        self.lik = float(np.exp(-0.5 * maha) / np.sqrt((2 * np.pi)**2 * det_S))
        return maha


class IMMFilter:
    """
    Simplified two-mode IMM for release speed estimation.

    Mode 0 (ballistic): standard gravity-only flight, used for the
    entire delivery from release to just before the bounce zone.
    Mode 1 (occluded):  coasting model with inflated process noise,
    activated when the tracker loses the ball mid-flight.

    We intentionally omit bounce and post-bounce modes because we only
    need the release speed, which is fully determined before any bounce
    event occurs.
    """

    def __init__(self, cam, x0, P0, fps):
        self.cam = cam
        self.dt  = 1.0 / fps
        self.N   = 2                  # ballistic + occluded
        self.mu  = np.array([0.92, 0.08])
        self.Ptr = IMM_TRANSITION.copy()

        # ballistic mode: tight process noise, ball is in clean flight
        Q_flight = np.diag([0.01, 0.005, 0.005, 0.5, 0.3, 0.5])
        # occluded mode: wider noise to coast through missing detections
        Q_coast  = np.diag([0.05, 0.02,  0.02,  2.0, 1.0, 2.0])

        self.modes = [
            UKFMode("ballistic", _f_ballistic, Q_flight, x0, P0, cam),
            UKFMode("occluded",  _f_ballistic, Q_coast,  x0, P0, cam),
        ]

    def _mix(self):
        """IMM interaction step: blend mode states before prediction."""
        c = np.zeros(self.N)
        for j in range(self.N):
            for i in range(self.N):
                c[j] += self.Ptr[i, j] * self.mu[i]
            c[j] = max(c[j], 1e-30)

        omega = np.zeros((self.N, self.N))
        for i in range(self.N):
            for j in range(self.N):
                omega[i, j] = self.Ptr[i, j] * self.mu[i] / c[j]

        for j in range(self.N):
            x_mix = sum(omega[i, j] * self.modes[i].x for i in range(self.N))
            P_mix = np.zeros((6, 6))
            for i in range(self.N):
                d = self.modes[i].x - x_mix
                P_mix += omega[i, j] * (self.modes[i].P + np.outer(d, d))
            self.modes[j].x = x_mix
            self.modes[j].P = P_mix
        return c

    def step(self, z, R, status, misses_count):
        """One full IMM cycle: mix, predict, update, reweight."""
        c = self._mix()

        for m in self.modes:
            m.predict(self.dt)

        has_measurement = (z is not None) and (status in ('det', 'hsv'))

        if has_measurement:
            for m in self.modes:
                maha = m.update(z, R)
                if maha > 16.0:
                    m.lik *= 0.01     # gate out wildly inconsistent obs
        else:
            for m in self.modes:
                m.lik = 1.0           # no measurement, all modes equally likely
            # nudge occluded probability up when tracker is missing
            if status in ('pred', 'miss'):
                self.mu[1] = min(0.95, self.mu[1] * 1.3)
            if misses_count > 5:
                self.mu[1] = min(0.95, self.mu[1] * 1.5)

        # Bayesian mode probability update
        for j in range(self.N):
            self.mu[j] = self.modes[j].lik * c[j]
        total = self.mu.sum()
        if total > 1e-30:
            self.mu /= total
        else:
            self.mu = np.ones(self.N) / self.N

    def fused_state(self):
        """Probability-weighted state across both modes."""
        return sum(self.mu[j] * self.modes[j].x for j in range(self.N))

    def speed_mps(self):
        """3D speed magnitude from the fused velocity components."""
        x = self.fused_state()
        return float(np.sqrt(x[3]**2 + x[4]**2 + x[5]**2))


# ═══════════════════════════════════════════════════════════════════════════════
# 3D STATE INITIALISATION
# ═══════════════════════════════════════════════════════════════════════════════

def _init_3d_state(obs_list, cam, fps):
    """
    Bootstrap a 3D state vector from the first few 2D pixel observations.
    Back-projects the average pixel position onto a ray, then places the
    ball at a plausible depth along that ray with a typical fast-medium
    bowling speed prior (~35 m/s).
    """
    n   = min(6, len(obs_list))
    obs = obs_list[:n]
    u_avg = np.mean([o['u'] for o in obs])
    v_avg = np.mean([o['v'] for o in obs])

    ray   = cam.back_project_ray(u_avg, v_avg)
    # place the ball roughly 18m down the pitch ray
    t_ray = 18.0 / ray[0] if abs(ray[0]) > 1e-4 else 18.0
    p     = CAM_POS_WORLD + t_ray * ray
    p[0]  = np.clip(p[0], 10.0, 22.0)
    p[1]  = np.clip(p[1], -2.0,  2.0)
    p[2]  = np.clip(p[2],  1.0,  2.8)

    speed = 35.0   # reasonable fast-medium prior (m/s)
    if n >= 2:
        du = obs[-1]['u'] - obs[0]['u']
        dv = obs[-1]['v'] - obs[0]['v']
        # vertical pixel motion maps roughly to vertical velocity
        vz = np.clip(-2.0 + (-dv / max(abs(du), 1)) * 3.0, -5.0, 5.0)
        vy = np.clip((du / max(abs(du) + abs(dv), 1)) * 2.0, -3.0, 3.0)
        vx = -np.sqrt(max(speed**2 - vy**2 - vz**2, 100.0))
    else:
        vx, vy, vz = -35.0, 0.0, -1.5

    x0 = np.array([p[0], p[1], p[2], vx, vy, vz])
    P0 = np.diag([4.0, 1.0, 0.5, 50.0, 10.0, 10.0])
    return x0, P0


# ═══════════════════════════════════════════════════════════════════════════════
# TRAJECTORY FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════════

def fit_parabola(x, y):
    """
    Fit parabola through points. Physics: ball under gravity follows parabola.
    Returns coefficients for y = ax^2 + bx + c
    """
    if len(x) < 3:
        return None
    try:
        return np.polyfit(x, y, 2)
    except Exception:
        return None


def smooth_trajectory_physics(x_raw, y_raw, status_arr=None):
    """
    Smooth using parabolic fits - matches real ball physics.
    Cricket ball: parabola down, bounce, parabola up then down.
    """
    n = len(x_raw)
    if n < MIN_POINTS:
        return x_raw.copy(), y_raw.copy(), None

    bounce_idx = None
    dy = np.diff(y_raw)

    for i in range(2, len(dy) - 1):
        if dy[i-1] > 0 and dy[i] < 0:
            local_range = y_raw[max(0, i-2):min(n, i+3)]
            if np.ptp(local_range) > BOUNCE_THRESHOLD:
                bounce_idx = i
                break

    if bounce_idx is None:
        coeffs = fit_parabola(x_raw, y_raw)
        if coeffs is not None:
            y_smooth = np.polyval(coeffs, x_raw)
            return x_raw.copy(), y_smooth, None
        return x_raw.copy(), y_raw.copy(), None

    x_pre, y_pre   = x_raw[:bounce_idx+1], y_raw[:bounce_idx+1]
    x_post, y_post = x_raw[bounce_idx:],   y_raw[bounce_idx:]

    coeffs_pre = fit_parabola(x_pre, y_pre)

    # Post-bounce: weight HSV recoveries at half the influence of YOLO dets
    # so noisy transition-zone points don't distort the fitted curve.
    if status_arr is not None and len(x_post) >= 3:
        status_post = status_arr[bounce_idx:]
        w_post = np.where(status_post == 'hsv', 2.0, 1.0)
        try:
            coeffs_post = np.polyfit(x_post, y_post, 2, w=w_post)
        except Exception:
            coeffs_post = fit_parabola(x_post, y_post)
    else:
        coeffs_post = fit_parabola(x_post, y_post)

    y_smooth_pre  = np.polyval(coeffs_pre,  x_pre)  if coeffs_pre  is not None else y_pre.copy()
    y_smooth_post = np.polyval(coeffs_post, x_post) if coeffs_post is not None else y_post.copy()

    x_smooth = np.concatenate([x_pre, x_post[1:]])
    y_smooth = np.concatenate([y_smooth_pre, y_smooth_post[1:]])

    bounce_pt = (x_raw[bounce_idx], y_smooth_pre[-1])

    return x_smooth, y_smooth, bounce_pt


def find_cutoff(x, y, bounce_idx):
    """
    Find where to cut trajectory - usually bat contact.
    Looks for sharp direction change after bounce.
    """
    if bounce_idx is None:
        return len(x) - 1

    for i in range(bounce_idx + 2, len(x) - 1):
        v1 = np.array([x[i] - x[i-1], y[i] - y[i-1]])
        v2 = np.array([x[i+1] - x[i], y[i+1] - y[i]])

        mag1, mag2 = np.linalg.norm(v1), np.linalg.norm(v2)
        if mag1 < 0.5 or mag2 < 0.5:
            continue

        cos_ang = np.clip(np.dot(v1, v2) / (mag1 * mag2), -1, 1)
        angle   = np.degrees(np.arccos(cos_ang))

        if angle > ANGLE_CUTOFF:
            return i

    return len(x) - 1


def _clean_detections(x_arr, y_arr, frames_arr, status_arr):
    """
    Remove false-positive detections that corrupt the parabolic fits.

    The tracker frequently locks onto a static object (ceiling light,
    sight-screen edge) before the ball is bowled.  These produce a
    near-stationary cluster followed by a huge spatial jump when the
    real ball enters the frame.  We detect this onset jump and discard
    everything before it.

    We also discard unreliable HSV-recovery detections in the gap
    between the pre-bounce and post-bounce YOLO clusters, since these
    often track the wrong blob after the ball changes direction.
    """
    n = len(x_arr)
    if n < 2:
        return x_arr, y_arr, frames_arr, status_arr

    # --- Step 1: remove pre-delivery false positives ---
    # Walk forward and find the first spatial jump exceeding 100 px.
    # Everything before that jump is a static FP (ceiling, sight-screen).
    ONSET_JUMP_PX = 100.0
    jumps = np.sqrt(np.diff(x_arr)**2 + np.diff(y_arr)**2)
    onset_indices = np.where(jumps >= ONSET_JUMP_PX)[0]

    if len(onset_indices) > 0:
        # The real delivery starts at the destination of the large jump
        start = onset_indices[0] + 1
        x_arr      = x_arr[start:]
        y_arr      = y_arr[start:]
        frames_arr = frames_arr[start:]
        if status_arr is not None:
            status_arr = status_arr[start:]

    # --- Step 2: remove unreliable HSV detections in the bounce gap ---
    # Find the largest frame gap between consecutive YOLO 'det' points.
    # Any HSV-only detections inside that gap are likely tracking the
    # wrong blob (pitch mark, shadow, crease) and would distort the fit.
    if status_arr is not None and len(x_arr) > 0:
        det_mask = (status_arr == 'det') | (status_arr == 'detected')
        det_indices = np.where(det_mask)[0]

        # Only filter if we have enough YOLO detections on both sides
        if len(det_indices) >= 6:
            det_frames = frames_arr[det_indices]
            gaps = np.diff(det_frames)

            if len(gaps) > 0:
                biggest = int(np.argmax(gaps))
                gap_start_frame = det_frames[biggest]
                gap_end_frame   = det_frames[biggest + 1]

                # If the gap is large enough to be a real bounce gap
                # (not just a 1-2 frame miss), remove HSV-only points
                # that fall inside it
                if gaps[biggest] > 5:
                    # Reference: last YOLO det before the gap
                    ref_idx = det_indices[biggest]
                    x_ref   = x_arr[ref_idx]
                    y_ref   = y_arr[ref_idx]
                    f_ref   = frames_arr[ref_idx]

                    # Speed gate: keep HSV whose implied speed from the last
                    # det is within a plausible range.  Near-static blobs
                    # (pitch marks, shadows) have very low speed; wildly
                    # displaced tracks have very high speed.
                    MIN_SPEED = 10.0  # px/frame
                    MAX_SPEED = 50.0  # px/frame

                    keep = np.ones(len(x_arr), dtype=bool)
                    for i in range(len(x_arr)):
                        in_gap = (frames_arr[i] > gap_start_frame and
                                  frames_arr[i] < gap_end_frame)
                        is_hsv = (status_arr[i] == 'hsv')
                        if in_gap and is_hsv:
                            frame_gap = frames_arr[i] - f_ref
                            if frame_gap > 0:
                                dist  = np.sqrt((x_arr[i] - x_ref)**2 +
                                                (y_arr[i] - y_ref)**2)
                                speed = dist / frame_gap
                                if not (MIN_SPEED <= speed <= MAX_SPEED):
                                    keep[i] = False
                            else:
                                keep[i] = False

                    x_arr      = x_arr[keep]
                    y_arr      = y_arr[keep]
                    frames_arr = frames_arr[keep]
                    status_arr = status_arr[keep]

    return x_arr, y_arr, frames_arr, status_arr


def load_trajectory_from_rows(csv_rows):
    """
    Build trajectory data from in-memory CSV rows (list of dicts).
    Equivalent to trajectorywriter.load_trajectory() but works on in-memory data.

    Applies noise removal (pre-delivery FPs, gap HSV) before passing
    clean data to smooth_trajectory_physics for two-parabola fitting.
    """
    df = pd.DataFrame(csv_rows)

    # Keep only rows with valid spatial data and real detection status
    mask = df['x'].replace('', np.nan).notna() & df['y'].replace('', np.nan).notna()
    if 'status' in df.columns:
        mask &= df['status'].isin(['det', 'hsv', 'detected'])

    valid = df[mask].reset_index(drop=True)

    if len(valid) < MIN_POINTS:
        raise ValueError(f"Need at least {MIN_POINTS} points, got {len(valid)}")

    x_raw  = valid['x'].values.astype(float)
    y_raw  = valid['y'].values.astype(float)
    frames = valid['frame'].values.astype(int)
    status = valid['status'].values.astype(str) if 'status' in valid.columns else None

    # Clean the detections: remove ceiling FPs and gap HSV noise
    x_raw, y_raw, frames, status = _clean_detections(x_raw, y_raw, frames, status)

    if len(x_raw) < MIN_POINTS:
        raise ValueError(f"Need at least {MIN_POINTS} points after cleaning, "
                         f"got {len(x_raw)}")

    # Two piecewise parabola fitting (unchanged logic)
    x_smooth, y_smooth, bounce_pt = smooth_trajectory_physics(x_raw, y_raw, status)

    bounce_idx = None
    if bounce_pt is not None:
        dists      = (x_smooth - bounce_pt[0])**2 + (y_smooth - bounce_pt[1])**2
        bounce_idx = int(np.argmin(dists))

    cutoff  = find_cutoff(x_smooth, y_smooth, bounce_idx)
    x_final = x_smooth[:cutoff+1]
    y_final = y_smooth[:cutoff+1]

    pts = np.column_stack([x_final, y_final]).astype(np.int32)

    return {
        'points':      pts,
        'bounce':      bounce_pt,
        'start_frame': int(frames[0]),
        'end_frame':   int(frames[min(cutoff, len(frames)-1)]),
    }


def draw_overlay(frame, traj_data, color, release_kmh=None):
    """
    Draw trajectory polyline and bounce marker onto the frame.
    Optionally overlay the release speed as text.
    """
    pts    = traj_data['points']
    bounce = traj_data['bounce']

    if len(pts) < 2:
        return frame

    cv2.polylines(frame, [pts], False, color, 2, cv2.LINE_AA)

    if bounce is not None:
        cx, cy = int(bounce[0]), int(bounce[1])
        cv2.circle(frame, (cx, cy), 12, (255, 255, 255), 2, cv2.LINE_AA)
        cv2.circle(frame, (cx, cy),  8, color,           2, cv2.LINE_AA)

    # speed text panel
    if release_kmh and release_kmh > 0:
        txt   = f"Release: {release_kmh:.0f} km/h"
        font  = cv2.FONT_HERSHEY_SIMPLEX
        sc, th = 0.9, 2
        pad    = 10
        tw, line_h = cv2.getTextSize(txt, font, sc, th)[0]
        line_h += 8

        # semi-transparent background box
        ov = frame.copy()
        cv2.rectangle(ov, (pad, pad), (pad + tw + 2 * pad, pad + line_h + pad),
                      (0, 0, 0), -1)
        cv2.addWeighted(ov, 0.55, frame, 0.45, 0, frame)
        cv2.putText(frame, txt, (2 * pad, pad + line_h),
                    font, sc, (255, 255, 255), th, cv2.LINE_AA)

    return frame


# ═══════════════════════════════════════════════════════════════════════════════
# IMM SPEED ESTIMATION (release only)
# ═══════════════════════════════════════════════════════════════════════════════

def run_imm_speed(csv_rows, fps):
    """
    Run the simplified two-mode IMM + UKF on trajectory detections.
    Returns only the release speed estimate; bounce speed is not computed.
    """
    df = pd.DataFrame(csv_rows)
    df['x'] = pd.to_numeric(df['x'], errors='coerce')
    df['y'] = pd.to_numeric(df['y'], errors='coerce')

    mask = df['x'].notna() & df['y'].notna()
    if 'status' in df.columns:
        mask &= df['status'].isin(['det', 'hsv', 'detected'])
    valid = df[mask].reset_index(drop=True)

    if len(valid) < MIN_POINTS:
        print(f"[IMM] Only {len(valid)} points -- skipping.")
        return {"imm_success": False}

    cam = CameraModel()

    obs_list = [
        {'frame': int(r['frame']), 'u': float(r['x']), 'v': float(r['y']),
         'status': str(r.get('status', 'det')), 'misses': int(r.get('misses', 0))}
        for _, r in valid.iterrows()
    ]

    # build a frame-indexed lookup so we can step through every frame
    all_obs = {}
    for _, row in df.iterrows():
        fi  = int(row['frame'])
        has = (not pd.isna(row.get('x', np.nan))
               and str(row.get('status', '')) in ('det', 'hsv', 'detected'))
        all_obs[fi] = {
            'u':      float(row['x']) if has else None,
            'v':      float(row['y']) if has else None,
            'status': str(row.get('status', 'miss')),
            'misses': int(row.get('misses', 0)),
        }

    x0, P0 = _init_3d_state(obs_list, cam, fps)
    print(f"[IMM] Init: pos=({x0[0]:.1f},{x0[1]:.1f},{x0[2]:.1f})m "
          f"vel=({x0[3]:.1f},{x0[4]:.1f},{x0[5]:.1f})m/s")

    imm     = IMMFilter(cam, x0, P0, fps)
    first_f = obs_list[0]['frame']
    last_f  = obs_list[-1]['frame']
    speeds  = []

    for fi in range(first_f, last_f + 1):
        o = all_obs.get(fi, {'u': None, 'v': None, 'status': 'miss', 'misses': 0})
        if o['u'] is not None:
            z   = np.array([o['u'], o['v']])
            sig = MEAS_SIGMA_DET if o['status'] == 'det' else MEAS_SIGMA_HSV
            R   = np.diag([sig**2, sig**2])
        else:
            z = None
            R = np.diag([MEAS_SIGMA_NONE**2] * 2)

        imm.step(z, R, o['status'], o['misses'])
        speeds.append(imm.speed_mps())

    # convert to km/h and smooth with a 5-frame moving average
    speeds = np.array(speeds) * 3.6
    if len(speeds) >= 5:
        speeds = np.convolve(speeds, np.ones(5) / 5, mode='same')

    # release speed = robust median of the first few frames
    win   = min(8, len(speeds))
    rel   = speeds[:win]
    med   = np.median(rel)
    clean = rel[rel < 2.0 * med]    # reject outlier spikes
    release = float(np.median(clean)) if len(clean) > 0 else float(med)
    release = float(np.clip(release, 0.0, 165.0))   # sane upper bound

    print(f"[IMM] Release: {release:.1f} km/h")

    return {
        "imm_success":       True,
        "release_speed_kmh": release,
        "speeds_kmh":        speeds,
        "first_frame":       first_f,
    }


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN PIPELINE
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    out_dir = Path(OUT_DIR)
    out_dir.mkdir(parents=True, exist_ok=True)

    tracker_yaml = out_dir / "bytetrack_custom.yaml"
    write_bytetrack_yaml(tracker_yaml)

    # ── Step 1: detection & tracking ─────────────────────────────────────────
    print("=" * 60)
    print("  Detection & Tracking  (YOLO + ByteTrack + HSV)")
    print("=" * 60)

    model  = YOLO(MODEL_PATH)
    stream = model.track(
        source=VIDEO_PATH, imgsz=IMGSZ, conf=CONF, iou=IOU, device=DEVICE,
        classes=CLASSES, tracker=str(tracker_yaml), persist=True, stream=True,
        verbose=False, save=False,
    )

    writer       = None
    video_fps    = 30.0
    csv_rows     = []
    active_id    = None
    last_pos     = None
    vel          = np.array([0.0, 0.0], dtype=float)
    misses       = 0
    hsv_model    = None
    last_box_area = None

    for fi, r in enumerate(stream):
        frame = r.orig_img
        if frame is None:
            continue

        if writer is None:
            h, w = frame.shape[:2]
            cap_tmp = cv2.VideoCapture(VIDEO_PATH)
            if cap_tmp.isOpened():
                fps_val = cap_tmp.get(cv2.CAP_PROP_FPS)
                if fps_val and fps_val > 0:
                    video_fps = fps_val
            cap_tmp.release()
            fourcc = cv2.VideoWriter_fourcc(*"mp4v")
            writer = cv2.VideoWriter(
                str(out_dir / "annotated_output.mp4"), fourcc, video_fps, (w, h))

        candidates = []
        if r.boxes is not None and len(r.boxes) > 0:
            xyxy  = r.boxes.xyxy.cpu().numpy()
            confs = r.boxes.conf.cpu().numpy()
            clss  = r.boxes.cls.cpu().numpy().astype(int)
            ids   = None
            if getattr(r.boxes, "id", None) is not None:
                ids = r.boxes.id.cpu().numpy().astype(int)
            for i in range(len(xyxy)):
                x1, y1, x2, y2 = xyxy[i]
                if MIN_BOX_AREA_PX > 0 and area_xyxy(x1, y1, x2, y2) < MIN_BOX_AREA_PX:
                    continue
                candidates.append({
                    "xyxy": (float(x1), float(y1), float(x2), float(y2)),
                    "conf": float(confs[i]),
                    "cls":  int(clss[i]),
                    "id":   int(ids[i]) if ids is not None else None,
                })

        pred = None
        if last_pos is not None:
            pred = (last_pos[0] + float(vel[0]), last_pos[1] + float(vel[1]))

        chosen = None
        gate   = GATE_RADIUS_PX + misses * GATE_GROW_PER_MISS

        if active_id is None:
            if candidates:
                chosen    = max(candidates, key=lambda d: d["conf"])
                active_id = chosen["id"]
        else:
            same_id = [d for d in candidates if d["id"] == active_id]
            pool    = same_id if same_id else candidates
            if pool and pred is not None:
                best = min(pool, key=lambda d: dist(center_xyxy(*d["xyxy"]), pred))
                if dist(center_xyxy(*best["xyxy"]), pred) <= gate:
                    chosen = best
            elif pool:
                chosen = max(pool, key=lambda d: d["conf"])

        hsv_recovered = False
        if chosen is not None and ENABLE_HSV_RECOVERY:
            hsv_model     = _learn_hsv_model(frame, chosen["xyxy"])
            x1, y1, x2, y2 = chosen["xyxy"]
            last_box_area = area_xyxy(x1, y1, x2, y2)

        if chosen is None and ENABLE_HSV_RECOVERY and hsv_model is not None and pred is not None:
            Hh, Ww = frame.shape[:2]
            half   = int(gate + HSV_ROI_PAD_PX)
            rx1, ry1, rx2, ry2 = _roi_from_center(pred[0], pred[1], half, Ww, Hh)
            bb = _hsv_blob_in_roi(frame, (rx1, ry1, rx2, ry2), hsv_model, pred_xy=pred)
            if bb is not None:
                chosen        = {"xyxy": bb, "conf": 0.0, "cls": 0, "id": active_id}
                hsv_recovered = True

        status = "miss"
        if chosen is not None:
            cx, cy = center_xyxy(*chosen["xyxy"])
            if last_pos is not None:
                new_vel = np.array([cx - last_pos[0], cy - last_pos[1]], dtype=float)
                vel     = 0.7 * vel + 0.3 * new_vel
            last_pos = (cx, cy)
            misses   = 0
            status   = "hsv" if hsv_recovered else "det"
            if chosen["id"] is not None:
                active_id = chosen["id"]
        else:
            misses += 1
            status  = "pred" if pred is not None else "miss"
            if misses > MAX_MISSES:
                active_id     = None
                last_pos      = None
                vel[:]        = 0.0
                hsv_model     = None
                last_box_area = None
                misses        = 0
                status        = "reset"

        vis = frame.copy()
        if chosen is not None:
            x1, y1, x2, y2 = map(int, chosen["xyxy"])
            cv2.rectangle(vis, (x1, y1), (x2, y2), (0, 255, 0), 2)
        if writer is not None:
            writer.write(vis)

        csv_rows.append({
            "frame":  fi,
            "status": status,
            "id":     active_id if active_id is not None else "",
            "x":      last_pos[0] if last_pos is not None else "",
            "y":      last_pos[1] if last_pos is not None else "",
            "vx":     float(vel[0]),
            "vy":     float(vel[1]),
            "gate":   gate,
            "misses": misses,
        })

        if fi % 100 == 0:
            print(f"  frame {fi} …", end='\r')

    if writer is not None:
        writer.release()

    csv_path = out_dir / "trajectory.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(csv_rows[0].keys()))
        w.writeheader(); w.writerows(csv_rows)
    print(f"\n  Tracking done. CSV: {csv_path}")

    # ── Step 2: IMM + UKF release speed ──────────────────────────────────────
    print("\n" + "=" * 60)
    print("  IMM + UKF Release Speed Estimation")
    print("=" * 60)
    imm_res = run_imm_speed(csv_rows, video_fps)

    release_kmh = imm_res.get("release_speed_kmh", 0.0) if imm_res.get("imm_success") else 0.0

    # ── Step 3: trajectory smoothing ─────────────────────────────────────────
    print("\n" + "=" * 60)
    print("  Trajectory Smoothing  (parabolic)")
    print("=" * 60)
    try:
        traj = load_trajectory_from_rows(csv_rows)
        print(f"  {len(traj['points'])} pts, "
              f"frames {traj['start_frame']}--{traj['end_frame']}")
        if traj['bounce']:
            print(f"  Bounce at ({traj['bounce'][0]:.1f}, {traj['bounce'][1]:.1f})")
    except ValueError as e:
        print(f"  Trajectory failed: {e}")
        return

    # ── Step 4: render final video ───────────────────────────────────────────
    print("\n" + "=" * 60)
    print("  Rendering overlay video")
    print("=" * 60)

    ann_path = str(out_dir / "annotated_output.mp4")
    cap = cv2.VideoCapture(ann_path)
    if not cap.isOpened():
        raise IOError(f"Can't open annotated video: {ann_path}")

    fps_v = cap.get(cv2.CAP_PROP_FPS)
    w     = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    h     = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    print(f"  {w}x{h}, {fps_v:.1f}fps, {total} frames")

    out = cv2.VideoWriter(OUTPUT_VIDEO, cv2.VideoWriter_fourcc(*'mp4v'), fps_v, (w, h))

    fn = 0
    while True:
        ret, frame = cap.read()
        if not ret:
            break
        if fn >= traj['start_frame']:
            draw_overlay(frame, traj, LINE_COLOR, release_kmh)
        out.write(frame)
        fn += 1
        if fn % 50 == 0:
            print(f"  {100 * fn / max(total, 1):.0f}%", end='\r')

    cap.release()
    out.release()

    print(f"\n" + "=" * 60)
    print("  DONE")
    print("=" * 60)
    print(f"  Output video : {OUTPUT_VIDEO}")
    print(f"  Trajectory   : {csv_path}")
    if release_kmh:
        print(f"  Release speed: {release_kmh:.1f} km/h")


if __name__ == "__main__":
    main()